config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    resources :comments, only: [:create]
  end
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :ticket
  belongs_to :user

end

app/models/ticket.rb
class Ticket < ApplicationRecord

    enum status: [:new_ticket, :pending, :resolved]
    enum priority: [:low, :medium, :high, :urgent]
    before_destroy :delete_from_csv

    validates_presence_of :name, :subject

    has_many :comments, dependent: :destroy
    belongs_to :assigned_to, class_name: 'User', optional: true
    belongs_to :creator, class_name: 'User', foreign_key: 'created_by'

    def save_to_csv
        csv_path = Rails.root.join('tickets.csv')
        CSV.open(csv_path, "a+") do |csv|
            csv << [nil, name, subject, content, status, priority, created_by]
        end
    end

    def has_non_empty_comments?
        comments.any? { |comment| comment.content.present? }
    end

    def delete_from_csv
        csv_path = Rails.root.join('tickets.csv').to_s
        `sed -i '/^#{self.id},/d' #{csv_path}`
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :assigned_tickets, foreign_key: :assigned_to_id
    has_many :created_tickets, class_name: 'Ticket', foreign_key: :created_by
    enum role: [:regular, :manager]
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def authenticate_manager!
        unless logged_in? && current_user.manager?
            redirect_to root_path, alert: "Only managers can access this page."
        end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    before_action :authenticate_manager!

    def create
        @ticket = Ticket.find(params[:ticket_id])
        @comment = @ticket.comments.new(comment_params)
        @comment.user = current_user

        if @comment.save
            redirect_to ticket_path(@ticket), notice: 'Comment added successfully!'
        else
            redirect_to ticket_path(@ticket), alert: 'Comment cannot be empty!'
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:content)
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
    
    def create
        user = User.find_by_email(params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to tickets_path
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

    before_action :authenticate_manager!, only: [:index, :update, :destroy]

    def new
        @ticket = Ticket.new
    end

    def index
        @tickets = Ticket.all
        @ticket_counts = Ticket.group(:status).count
    end

    def show
        @ticket = Ticket.find(params[:id])
    end

    def create
        @ticket = Ticket.new(ticket_params)
        @ticket.created_by = current_user.id
        if @ticket.valid?
            @ticket.save_to_csv
            redirect_to tickets_path, notice: 'Ticket was successfully created.'
        else
            render :new
        end
    end
    
    def update
        @ticket = Ticket.find(params[:id])
        if @ticket.update(ticket_params)
            redirect_to tickets_path, notice: 'Ticket was successfully updated.'
        else
            render :edit
        end
    end
    
    def destroy
        @ticket = Ticket.find(params[:id])
        @ticket.destroy
        redirect_to tickets_path, notice: 'Ticket was successfully deleted.'
    end
    
    private
    
    def ticket_params
        params.require(:ticket).permit(:name, :email, :subject, :content, :status, :priority, :assigned_to_id, :created_by)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to tickets_path
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupportTicketSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </body>
</html>
</br></br>

<% if logged_in? %>
  <%= link_to "Sign Out - #{current_user.email}", logout_path %></br></br>
  <%= link_to 'New Ticket', new_ticket_path %>

<% else %>
  <%= link_to 'Sign In', login_path %>
<% end %>

app/views/tickets/index.html.erb
<h1>All Tickets</h1>

<style>
    table {
        width: 100%;
    }
    td {
        text-align: center;
    }

</style>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Created By</th>
            <th>Subject</th>
            <th>Content</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @tickets.each do |ticket| %>
            <tr>
                <td><%= ticket.name %></td>
                <td><%= User.find(ticket.created_by).email %></td>
                <td><%= ticket.subject %></td>
                <td><%= ticket.content %></td>
                <td>
                    <%= form_for ticket, url: ticket_path(ticket), method: :patch do |f| %>
                    <% tickets_options = Ticket.statuses.keys.map { |status| [status.humanize, status, { disabled: (status == 'resolved' && !ticket.has_non_empty_comments?) }] } %>
                        <%= f.select :status, tickets_options, {}, onchange: 'this.form.submit();' %>
                    <% end %>
                </td>
                <td><%= button_to 'Show', ticket_path(ticket), method: :get %></td>
                <td><%= button_to 'Delete', ticket_path(ticket), method: :delete %></td>
            </tr>
        <% end %>
    </tbody>
</table>
</br></br>

<p>
    <b>Statistics:</b></br>
    <% Ticket.statuses.keys.each do |status| %>
        <%= "#{status.humanize}: #{@ticket_counts[status] || 0}" %>
        </br>
    <% end %>
</p>

app/views/tickets/new.html.erb
<h1>Create a New Ticket</h1>

<%= form_for @ticket, data: { turbo: "false" } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </br>   </br>

    <%= f.label :subject %>
    <%= f.text_field :subject %>
    </br>   </br>


    <%= f.label :content %>
    <%= f.text_area :content %>
    </br>   </br>

    <%= f.label :priority %>
    <%= f.select :priority, Ticket.priorities.keys %>
    </br>   </br>

    <%= f.hidden_field :assigned_to_id, value: current_user.id %>
    </br>   </br>


    <%= f.submit "Create Ticket" %>
<% end %>

<% if @ticket&.errors.any? %>
    <div class="errors" style="color:red">
        <ul>
            <% @ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/tickets/show.html.erb
<h1><%= @ticket.subject %></h1>
<p><%= @ticket.content %></p>
</br></br>
<% if current_user.manager? %>
    <%= form_with model: [@ticket, @ticket.comments.build] do |f| %>
        <%= f.text_area :content, placeholder: 'Add comment' %>
        </br>
        <%= f.submit "Create Comment" %>
    <% end %>
<% end %>


<% non_empty_comments = @ticket.comments.reject { |comment| comment.content.blank? } %>
<% unless non_empty_comments.empty? %>
    <p><b>Comments</b></p>
    <ol>
        <% non_empty_comments.sort_by(&:id).each do |comment| %>
        <li>
            <p><%= comment.content %></p>
            <p>By: <%= comment&.user&.email %></p>
        </li>
        <% end %>
    </ol>
<% end %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user, data: { turbo: "false" } do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    </br>    </br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    </br>    </br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </br>    </br>

    <%= f.submit "Signup" %>
<% end %>


<% if @user&.errors.any? %>
    <div class="errors" style="color:red">
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>